version: '3'

services:
  backend:
    image: backend:latest
    container_name: ZTWbackend
    ports:
      - "8080:8080"


  keycloak:
    image: keycloak:latest
    container_name: ZTWkeycloak
    ports:
      - "8888:8888"
      - "9000:9000"
      - "8443:8443"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: checkers
      DB_VENDOR: h2

  frontend:
    build:
      context: ./front
    container_name: ZTWfrontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true




